---
- name: Provision GCP VM with Terraform
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Ensure working directory exists
      file:
        path: /tmp/tf-gcp
        state: directory

    - name: Copy Terraform configuration files
      copy:
        src: "{{ item }}"
        dest: /tmp/tf-gcp/
      with_items:
        - ../main.tf
        - ../variables.tf
        - ../outputs.tf

    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: /tmp/tf-gcp

    - name: Apply Terraform plan
      command: terraform apply -auto-approve
      args:
        chdir: /tmp/tf-gcp
      environment:
        GOOGLE_PROJECT: "{{ dialog_project_id }}"
        GOOGLE_REGION: "{{ dialog_region }}"
        GOOGLE_ZONE: "{{ dialog_zone }}"
        TF_VAR_project_id: "{{ dialog_project_id }}"
        TF_VAR_region: "{{ dialog_region }}"
        TF_VAR_zone: "{{ dialog_zone }}"
        TF_VAR_machine_type: "{{ dialog_machine_type }}"
        TF_VAR_vm_name: "{{ dialog_vm_name }}"
        TF_VAR_credentials_file: "{{ dialog_credentials_file }}"
