---
- name: Provision GCP VM from ManageIQ
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - google.cloud

  vars:
    project_id: "{{ dialog_project_id | default('optical-caldron-472316-u5') }}"
    zone: "{{ dialog_zone | default('us-west2-a') }}"
    region: "{{ dialog_region | default('us-west2') }}"
    machine_type: "{{ dialog_machine_type | default('e2-standard-2') }}"
    vm_name: "{{ dialog_vm_name | default('miq-test-vm') }}"

  tasks:
    - name: Create GCP VM
      google.cloud.gcp_compute_instance:
        name: "{{ vm_name }}"
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        # Tower will inject this automatically from the GCP-ServiceAccount credential
        service_account_email: "{{ lookup('env', 'GCP_SERVICE_ACCOUNT_EMAIL') }}"
        service_account_file: "{{ lookup('env', 'GCP_SERVICE_ACCOUNT_FILE') }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "projects/debian-cloud/global/images/family/debian-11"
        network_interfaces:
          - network: default
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        service_accounts:
          - email: "{{ lookup('env', 'GCP_SERVICE_ACCOUNT_EMAIL') }}"
            scopes:
              - https://www.googleapis.com/auth/cloud-platform
