---
- name: Provision GCP VM via Terraform Cloud
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # Workspace ID from Terraform Cloud
    tfc_workspace_id: "ws-AoELqx1SzRs6ZUn7"

    # Token file we already created on the VM
    tfc_token_file: "/var/lib/awx/credentials/tfc_token.txt"

  tasks:
    - name: Read Terraform Cloud token
      slurp:
        src: "{{ tfc_token_file }}"
      register: tfc_token_raw

    - name: Decode token
      set_fact:
        tfc_token: "{{ tfc_token_raw.content | b64decode }}"

    - name: Trigger Terraform Run in HCP
      uri:
        url: "https://app.terraform.io/api/v2/runs"
        method: POST
        headers:
          Authorization: "Bearer {{ tfc_token }}"
          Content-Type: "application/vnd.api+json"
        body_format: json
        body:
          data:
            attributes:
              is_destroy: false
              message: "Run triggered from ManageIQ provision.yml"
            type: runs
            relationships:
              workspace:
                data:
                  type: workspaces
                  id: "{{ tfc_workspace_id }}"
        status_code: 201
      register: run_response

    - name: Save Run ID for ManageIQ check_completed
      set_stats:
        data:
          miq_terraform_run_id: "{{ run_response.json.data.id }}"
