---
- name: Provision GCP VM
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    project_id: "{{ project_id }}"
    region: "{{ region }}"
    zone: "{{ zone }}"
    machine_type: "{{ machine_type }}"
    vm_name: "{{ vm_name }}"
    credentials_file: "{{ credentials_file }}"

  tasks:
    - name: Authenticate with GCP
      command: >
        gcloud auth activate-service-account
        --key-file {{ credentials_file }}

    - name: Create VM instance
      command: >
        gcloud compute instances create {{ vm_name }}
        --project {{ project_id }}
        --zone {{ zone }}
        --machine-type {{ machine_type }}
        --image-family debian-11
        --image-project debian-cloud

    - name: Notify ManageIQ playbook finished
      debug:
        msg: "Provision completed successfully"

    - name: Mark playbook as successful for ManageIQ
      set_stats:
        data:
          miq_playbook_status: "ok"
