---
- name: Provision GCP VM with Terraform
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    tf_dir: "{{ playbook_dir }}/.."
    credentials_file: "/var/lib/manageiq/keys/gcp-sa.json"

  tasks:
    - name: Generate terraform.tfvars.json
      copy:
        dest: "{{ tf_dir }}/terraform.tfvars.json"
        content: |
          {
            "project_id": "{{ dialog_project_id }}",
            "region": "{{ dialog_region }}",
            "zone": "{{ dialog_zone }}",
            "machine_type": "{{ dialog_machine_type }}",
            "vm_name": "{{ dialog_vm_name }}",
            "credentials_file": "{{ credentials_file }}"
          }

    - name: Run terraform init
      command: terraform init
      args:
        chdir: "{{ tf_dir }}"

    - name: Run terraform apply
      command: terraform apply -auto-approve
      args:
        chdir: "{{ tf_dir }}"
