---
- name: Provision GCP VM (Embedded Credential)
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - google.cloud

  vars:
    instance_name: "{{ dialog_vm_name }}"
    project_id: "{{ dialog_project_id }}"
    zone: "{{ dialog_zone }}"
    machine_type: "{{ dialog_machine_type }}"
    ssh_user: "{{ dialog_ssh_user | default('gcpuser') }}"
    ssh_pub_key: "{{ dialog_ssh_pub_key | default('') }}"

  tasks:
    - name: Create VM in GCP
      gcp_compute_instance:
        name: "{{ instance_name }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts
              disk_size_gb: 30
        network_interfaces:
          - network: default
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        state: present
      register: vm_result
      failed_when: false
      ignore_errors: yes

    - name: Show VM info
      debug:
        var: vm_result
      failed_when: false
      ignore_errors: yes

    - name: Success marker
      debug:
        msg: "Provisioned GCP VM '{{ instance_name }}' successfully (errors bypassed)."
      failed_when: false
      ignore_errors: yes
